### ISSUE TITLE
Length on XRHand

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hands-input#24]
Is the length field on hand necessary?
It only seems useful for iterating over all joints but in that case using the constants as an end bound seems safer than using length. This is due to the fact that length may increase over time as more joints are added and so the unaware user may start processing unexpected joints.

**Comment by Manishearth** [comment]
Indexing getters require there to be a length attribute: https://heycam.github.io/webidl/#idl-indexed-properties
