### ISSUE TITLE
Rough API surface

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hands-input#4]
This is the issue for working out a rough API surface. Some constraints I'd like to put forward:

 - It should be designed such that hand tracking will only run if requested.
 - Everything should be exposed as an XRSpace
 - Devices should have reasonable fallbacks for not supporting all joints

**Comment by Manishearth** [comment]
We can probably achieve the "will only run if requested" by making it a feature request.

My current thoughts are that we have something like


```webidl
partial interface XRInputSource {
   XRHand? hand;
}


interface XRHand {
     // returns non null if joint is supported
     // if joint is supported but currently untracked, joint.space
     // will return null when used in getPose
     getter XRJoint(unsigned short jointIndex);
}


interface XRJoint {
   XRSpace space;
   // radius to be used for rendering joint
   float? radius;
   
   // joint constants:
   const unsigned short INDEX_PHALANGE_PROXIMAL = ..;
   // ... more joints
}
```

Furthermore we could have stuff indicating if a joint is emulated, etc.

**Comment by fordacious** [comment]
> Furthermore we could have stuff indicating if a joint is emulated

Important if we wish to support controller hand simulation e.g. SteamVR
